# Generated by Django 5.0.6 on 2024-06-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfo',
            old_name='country',
            new_name='city',
        ),
    ]
